services:
  server:
    image: ghcr.io/FoxHyena/furryPornHelperBot:latest
    build:
      context: .
    env_file: ./.env
    volumes:
      - ./photos:/usr/src/app/photos
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
